apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-zookeper
  name: social-albums-zookeper
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-zookeper
  template:
    metadata:
      labels:
        app: social-albums-zookeper
    spec:
      enableServiceLinks: false # Used to prevent Kubernetes environment variables to be injected into the pod and cause conflicts (https://github.com/confluentinc/schema-registry/issues/689#issuecomment-827716674)
      containers:
        - name: zookeper
          image: confluentinc/cp-zookeeper:7.6.1
          envFrom:
            - configMapRef:
                name: social-albums-zookeper-config
          ports:
            - containerPort: 2181
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 15
