apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-mysql
  name: mysql
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: config-secrets
          image: mysql:8.0.33
          name: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pvc
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc