apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-mysql
  name: social-albums-mysql
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-mysql
  template:
    metadata:
      labels:
        app: social-albums-mysql
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: mysql-config-secrets
          image: mysql:8.0.33
          name: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: social-albums-mysql-pvc
            - mountPath: /var/db/config
              name: mysql-schema-config-vol
        - livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: liveness-probe
      initContainers:
        - name: init-social-schema-config
          image: busybox:1.28
          command:
            - sh
            - -c
            - psql
            - -a -f
            - "/var/db/config/mysql-social-schema-config.sql"
        - name: init-keycloak-schema-config
          image: busybox:1.28
          command:
            - sh
            - -c
            - psql
            - -a -f
            - "/var/db/config/keycloak-create-schema-config.sql"
      volumes:
        - name: social-albums-mysql-pvc
          persistentVolumeClaim:
            claimName: social-albums-mysql-pvc
        - name: mysql-schema-config-vol
          configMap:
            name: mysql-config
            defaultMode: 420
            items:
              - key: mysql-social-schema-config
                path: mysql-social-schema-config.sql
              - key: keycloak-cretate-schema
                path: keycloak-create-schema-config.sql
