apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: social-albums 
  labels:
    pvc: mysql
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce