kind: Deployment
apiVersion: apps/v1
metadata:
  name: social-users-producer
  namespace: social-albums
  labels:
    app: social-users-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-users-producer
  template:
    metadata:
      labels:
        app: social-users-producer
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: users-producer-secrets
          - secretRef:
              name: social-albums-keycloak-config-secrets
        image: angelosnm/users-producer:58174ab-33
        env:
          - name: KAFKA_BROKER
            value: social-albums-kafka:29092
          - name: KAFKA_TOPIC_USERS
            value: users-topic
          - name: KAFKA_TOPIC_ARTISTS
            value: artists-topic
        name: social-users-producer
      initContainers:
        - name: wait-for-neo4j-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-neo4j 7687; do echo waiting for neo4j-service; sleep 2; done;
        - name: wait-for-kafka-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-kafka 29092; do echo waiting for kafka; sleep 2; done;