kind: Deployment
apiVersion: apps/v1
metadata:
  name: social-albums-api
  namespace: social-albums
  labels:
    app: social-albums-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-api
  template:
    metadata:
      labels:
        app: social-albums-api
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: social-albums-config
        image: angelosnm/social-albums:v2
        name: social-albums-api