apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: social-albums-api
  namespace: social-albums
spec:
  rules:
  - host: api.social-albums.cuccos.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: social-albums-api
            port:
              number: 5000
  tls:
  - hosts:
    - api.social-albums.cuccos.org
    secretName: api-social-albums-cuccos-org-tls