kind: Deployment
apiVersion: apps/v1
metadata:
  name: social-users-consumer
  namespace: social-albums
  labels:
    app: social-users-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-users-consumer
  template:
    metadata:
      labels:
        app: social-users-consumer
    spec:
      containers:
        - name: social-users-consumer
          image: angelosnm/users-consumer:334e6ab-58
          envFrom:
            - secretRef:
                name: social-albums-consumer-secrets
            - secretRef:
                name: social-albums-kafka-secrets
      initContainers:
        - name: wait-for-mysql-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-mysql 3306; do echo waiting for mysql-service; sleep 2; done;
        - name: wait-for-kafka-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-kafka 29092; do echo waiting for kafka; sleep 2; done;
