apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-kafka
  name: social-albums-kafka
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-kafka
  template:
    metadata:
      labels:
        app: social-albums-kafka
    spec:
      enableServiceLinks: false # Used to prevent Kubernetes environment variables to be injected into the pod and cause conflicts (https://github.com/confluentinc/schema-registry/issues/689#issuecomment-827716674)
      containers:
        - envFrom:
            - configMapRef:
                name: social-albums-kafka-config
          image: confluentinc/cp-kafka:7.5.0
          name: kafka
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 29093