apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: social-albums
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: external
  - port: 29092
    targetPort: 29092
    name: internal
  - port: 29093
    targetPort: 29093
    name: listener
  selector:
    app: kafka
  type: ClusterIP