kind: Deployment
apiVersion: apps/v1
metadata:
  name: social-albums-producer
  namespace: social-albums
  labels:
    app: social-albums-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-producer
  template:
    metadata:
      labels:
        app: social-albums-producer
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: mongo-config-secrets
        image: oulievancs/albums-producer:0.0.2
        name: social-albums-producer
      # imagePullSecrets:
      # - name: registry-creds
      initContainers:
        - name: wait-for-mongodb-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-mongo 27017; do echo waiting for mongodb-service; sleep 2; done;