kind: Deployment
apiVersion: apps/v1
metadata:
  name: social-albums-producer
  namespace: social-albums
  labels:
    app: social-albums-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-producer
  template:
    metadata:
      labels:
        app: social-albums-producer
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: albums-producer-secrets
          - secretRef:
              name: social-albums-keycloak-config-secrets
        name: social-albums-producer
      initContainers:
        - name: wait-for-mongodb-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-mongo 27017; do echo waiting for mongodb-service; sleep 2; done;
        - name: wait-for-kafka-pod
          image: busybox:1.28
          args:
            - /bin/sh
            - -c
            - until telnet social-albums-kafka 29092; do echo waiting for kafka; sleep 2; done;