apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: social-albums
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP