apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-keycloak
  name: social-albums-keycloak
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-keycloak
  template:
    metadata:
      labels:
        app: social-albums-keycloak
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: keycloak-config-secrets
        image: quay.io/keycloak/keycloak:24.0
        name: keycloak
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "start"
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /opt/keycloak/data
            name: social-albums-keycloak-pvc
      volumes:
        - name: social-albums-keycloak-pvc
          persistentVolumeClaim:
            claimName: social-albums-keycloak-pvc