apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: social-albums-neo4j
  name: social-albums-neo4j
  namespace: social-albums
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-albums-neo4j
  template:
    metadata:
      labels:
        app: social-albums-neo4j
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: neo4j-config-secrets
          image: neo4j:5.15.0
          name: neo4j
#          command:
#          - /bin/chown
#          - -R
#          - "neo4j:neo4j"
#          - /root/neo4j/conf
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - mountPath: /data
              name: social-albums-neo4j-pvc
#            - mountPath: /root/neo4j/conf
#              name: neo4j-social-config-vol
          livenessProbe:
            exec:
              command:
                - wget
                - http://127.0.0.1:7474
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
      volumes:
        - name: social-albums-neo4j-pvc
          persistentVolumeClaim:
            claimName: social-albums-neo4j-pvc
#        - name: neo4j-social-config-vol
#          configMap:
#            name: node4j-social-config
#            defaultMode: 420
#            items:
#              - key: neo4j.conf
#                path: node4j-social-config.conf