apiVersion: v1
kind: Service
metadata:
  labels:
    app: social-albums-neo4j
  name: social-albums-neo4j # https://stackoverflow.com/a/77261518
  namespace: social-albums
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: db
  selector:
    app: social-albums-neo4j
  type: ClusterIP