apiVersion: v1
kind: Service
metadata:
  labels:
    app: neo4j
  name: neo4j
  namespace: social-albums
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: db
  selector:
    app: neo4j
  type: ClusterIP